---
# tasks file for CentOSJoinDomain
- name: include distribution dependency variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution_file_variety }}.yml"

- name: Linux Join Active Directory Domain Tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution_file_variety }}.yml"