- name: Install Required Packages
  yum:
    name: "{{ package }}"
    state: present

- name: Checking Domain Join status
  command: id "{{ Join_User }}"
  register: ad_status
  changed_when: false
  ignore_errors: true

- name: Domain configs and Join {{ DomainName }}
  block:

    - name: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} into Domain {{ DomainName }}"
      command: /bin/bash -c "echo {{ Join_User_Pass }} | /usr/sbin/realm join --user={{ Join_User }} {{ DomainName }}"
      no_log: true

    - name: Allow user Login without FQDN
      lineinfile:
        backup: yes
        state: present
        dest: /etc/sssd/sssd.conf
        regexp: '^{{ item.search }}'
        line: '{{ item.replace }}'
      with_items:
        - { search: 'use_fully_qualified_names', replace: 'use_fully_qualified_names = False' }
        - { search: 'fallback_homedir', replace: 'fallback_homedir = /home/%u'}
        - { search: 'access_provider', replace: 'access_provider = simple'}
      notify: restart sssd
  when: ad_status.rc !=0