---

- name: First set all group logons to deny
  shell: "/usr/sbin/realm deny -a"

- name: Set the allowed groups that can log on with Active Directory credentials
  shell: '/usr/sbin/realm permit -g "{{ item }}"@{{ DomainName }}'
  with_list: "{{ set_allowed_login_group_membership_list }}"

...